version: '2.0'
services:
  nginx-service:
    container_name: nginx
    image: nginx:${BUILD_NUM}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 80:80
    networks:
      - nginx


networks:
  nginx:
