version: '2.0'
services:
  nginx-service:
    container_name: nginx
    build:
      context: /home/ubuntu/nginx/nginx/
      args:
        - VERSION=1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 80:80
    networks:
      - nginx


networks:
  nginx:
