# Basic provisioning example
---
- hosts: localhost
  gather_facts: no
  vars:
    access: ""
    secret: ""
    subnet_id: ""
    ami: ""
    region: ""
    key: ""
    key_path: ""
    sg_group: ""
    tag_name: "nginx"
    sqs_name: "sqs-nginx"
    lambda_name: "lambda-nginx"
    lambda_role: ""

  tasks:
  - name: Prompt
    pause: prompt="Please choose one of the following - deploy|terminate"
    register: arg1

  - name: Get git repository
    git:
      repo=https://github.com/ctepx25/nginx.git
      dest=/tmp/nginx
    when: arg1.user_input == "deploy"

  - name: Start instance
    ec2:
      aws_access_key: "{{access}}"
      aws_secret_key: "{{secret}}"
      region: "{{region}}"
      key_name: "{{key}}"
      instance_type: t2.micro
      image: "{{ami}}"
      wait: yes
      group_id: "{{sg_group}}"
      count: 1
      vpc_subnet_id: "{{subnet_id}}"
      assign_public_ip: yes
      instance_tags:
        Name: "{{tag_name}}"
    when: arg1.user_input == "deploy"

  - pause:
      minutes: 1
    when: arg1.user_input == "deploy"

  - name: get ip
    ec2_remote_facts:
      aws_access_key: "{{access}}"
      aws_secret_key: "{{secret}}"
      region: "{{region}}"
      filters:
        "tag:Name": "{{tag_name}}"
    register: ec2_remote_facts
  - debug: var=ec2_remote_facts['instances'][0]['public_ip_address']

  - name: Install dependences
    shell: ssh -i "{{key_path}}" -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@{{ ec2_remote_facts['instances'][0]['public_ip_address'] }} 'sudo apt-get update;sudo apt-get install docker.io docker-compose git -y; sudo apt-get remove apparmor -y'
    register: output
    when: arg1.user_input == "deploy"
  - debug: var=output.stdout_lines

  - name: Add ssh public key
    shell: ssh -i "{{key_path}}" -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@{{ ec2_remote_facts['instances'][0]['public_ip_address'] }} 'sudo cat /home/ubuntu/nginx/id_rsa.pub >> /root/.ssh/authorized_keys'
    register: output
    when: arg1.user_input == "deploy"
  - debug: var=output.stdout_lines

  - name: Clone Git repo
    shell: ssh -i "{{key_path}}" -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@{{ ec2_remote_facts['instances'][0]['public_ip_address'] }} 'git clone https://github.com/ctepx25/nginx.git'
    register: output
    when: arg1.user_input == "deploy"
  - debug: var=output.stdout_lines

  - name: Create nginx service
    shell: ssh -i "{{key_path}}" -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@{{ ec2_remote_facts['instances'][0]['public_ip_address'] }} 'cd /home/ubuntu/nginx/;sudo docker-compose -f docker-compose.yml up --build -d'
    register: output
    when: arg1.user_input == "deploy"
  - debug: var=output.stdout_lines
  
  - name: SQS
    sqs_queue:
      name: "{{sqs_name}}"
      aws_access_key: "{{access}}"
      aws_secret_key: "{{secret}}"
      region: "{{region}}"
      default_visibility_timeout: 120
      message_retention_period: 86400
      maximum_message_size: 1024
      delivery_delay: 30
      receive_message_wait_time: 20
    register: sqs_queue
    when: arg1.user_input == "deploy"
  - debug: var=sqs_queue['queue_arn']

  - name: Create Lambda function
    lambda:
      name: "{{lambda_name}}"
      state: present
      aws_access_key: "{{access}}"
      aws_secret_key: "{{secret}}"
      region: "{{region}}"
      zip_file: '/tmp/nginx/worker_function.zip'
      runtime: 'python2.7'
      handler: 'worker_function.worker_handler'
      role: "{{lambda_role}}"
    when: arg1.user_input == "deploy"

  - name: Add lambda trigger
    command: python3 lambda-trigger.py {{item}}
    with_items:
    - "{{sqs_queue['queue_arn']}} {{lambda_name}} {{region}} {{access}} {{secret}}"
    register: output
    when: arg1.user_input == "deploy"
  - debug: var=output.stdout_lines

  - name: Delete git folder
    file:
      state: absent
      path: '/tmp/nginx'
    when: arg1.user_input == "deploy"

  - name: Terminate instances
    ec2:
      aws_access_key: "{{access}}"
      aws_secret_key: "{{secret}}"
      region: "{{region}}"
      state: 'absent'
      instance_ids: "{{ec2_remote_facts['instances'][0]['id']}}"
    when: arg1.user_input == "terminate"

  - name: Delete Lambda function
    lambda:
      aws_access_key: "{{access}}"
      aws_secret_key: "{{secret}}"
      region: "{{region}}"
      name: "{{lambda_name}}"
      state: absent
    when: arg1.user_input == "terminate"

  - name: Delete sqs
    sqs_queue:
      aws_access_key: "{{access}}"
      aws_secret_key: "{{secret}}"
      region: "{{region}}"
      name: "{{sqs_name}}"
      state: absent
    when: arg1.user_input == "terminate"
